name: CI

on:
  push:
    branches: [ "main" ]
  pull_request: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pytest
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
